### ISSUE TITLE
Weird issue ?

### ISSUE THREAD

**Issue by hardcpp** [NVorbis/NVorbis#12]
Hello i was getting _prevPacketStart bigger than _prevPacketEnd after a seek in StreamDecoder
**it was doing an INFINITE loop**

i Changed line 335 operator == to >= and it fixed the issue for me (the result audio is valid)

**Comment by hardcpp** [comment]
I can do that, i also have a lot of out of range exception i will setup something for you to test.

Anyway good job for this ! out of 38k ogg file i got a success rate of 90%

**Comment by hardcpp** [comment]
Here you go captain 

https://puu.sh/H6Q5n/957b11ac3a.rar

My discord if you have any question HardCPP#1985

**Comment by ioctlLR** [comment]
OK, figured out the exception case: PageReader.ParsePageHeader(...) was adding the running packet size to the total page data size with each segment.  It should only add each segment's length.  Since the calculated length is truncated to uint, that issue caused the later packet data read to only read in 5,442 bytes of data instead of the correct 30.433 bytes for the problem page.  Oops!

Still trying to figure out the infinite loop.  I _think_ the packet seek logic is off by one, but I'm not sure how just yet.

**Comment by hardcpp** [comment]
Nice found !

**Comment by hardcpp** [comment]
any news sir ?

**Comment by ioctlLR** [comment]
Not yet.  Haven't been able to look at it much in the last couple days due to work demands.

**Comment by ioctlLR** [comment]
OK, finally made some progress...  Still not sure what's going on, precisely, but have found that PacketProvider.FindPacket(...) is calculating a different location than StreamDecoder; The page granulePos returned (page 90) is 368 before the requested seek position, but the first packet of the next page is only 128 samples long.  I _think_ the seek function is off by one (it should be a packet later), but I'm not yet sure why.

**Comment by ioctlLR** [comment]
Note: FindPacket is at least getting to the right page...  It's just missing on which packet (it thinks 0, but should be 1 or 2).

**Comment by hardcpp** [comment]
Ok nice, tell me when you need testing :)
