### ISSUE TITLE
Concat Header and a single page won't give correct PageSamples

### ISSUE THREAD

**Issue by vincenzoxx** [NVorbis/NVorbis#5]
I was trying to concat header with a single ogg page to get FirstGranulePosition ( in this case 0 ) but reading that stream with NVorbis  gives more samples than expected. Is there any reason why that happens?
![image](https://user-images.githubusercontent.com/50289647/78877889-d011f980-7a51-11ea-9b64-cbd254148aca.png)

Update.....
I've actually found out the problem. For some reason, Reading too fast from the stream causes it to give more samples.
Debugging ( simulating slow read )
![image](https://user-images.githubusercontent.com/50289647/78878996-9510c580-7a53-11ea-9f7b-9db6f9a7c118.png)
Without Debug ( fast read )
![image](https://user-images.githubusercontent.com/50289647/78879161-cd180880-7a53-11ea-8d6a-df7de6dca66e.png)

Update....
It might be possible that debug updates some properties as well.

**Comment by ioctlLR** [comment]
I'm honestly not sure what exactly you mean by "concat header" or "reading too fast".  Can you share your code (or at least a minimally-viable reproduction of the issue)?

How is this threaded?  Are there multiple threads accessing a given VorbisReader or Ogg.ContainerReader instance?  NVorbis isn't really thread-safe (there are a couple very specific scenarios that are supported, but I don't think they apply here)...

**Comment by vincenzoxx** [comment]
yes here I've a screenshot:
![image](https://user-images.githubusercontent.com/50289647/78906819-21d17880-7a80-11ea-8523-c9786cc7e42a.png)
there aren't multiple threads
here the code:
`public Ogg(byte[] oggPageBuffer, byte[] oggHeaderBuffer = null)
		{
			this.OggPageBuffer = oggPageBuffer;
			this.OggHeaderBuffer = oggHeaderBuffer ?? new byte[0];
			int totSamples = 0;
			byte[] holder;
			holder = new byte[8];
			Array.Copy(this.OggPageBuffer, 6, holder, 0, 8);
			LastGranulePosition = BitConverter.ToInt64(holder, 0);
			holder = new byte[4];
			Array.Copy(this.OggPageBuffer, 18, holder, 0, 4);
			PageSequenceNumber = BitConverter.ToUInt32(holder, 0);
			byte[] fullBuffer = new byte[this.OggPageBuffer.Length + this.OggHeaderBuffer.Length];
			Array.Copy(this.OggHeaderBuffer, 0, fullBuffer, 0, this.OggHeaderBuffer.Length);
			Array.Copy(this.OggPageBuffer, 0, fullBuffer, this.OggHeaderBuffer.Length, this.OggPageBuffer.Length);
			this._initializeVorbis = new Lazy<bool>(() =>
			{
				try
				{
					if (this.OggHeaderBuffer.Length > 0)
					{
						MemoryStream memoryStream = new MemoryStream(fullBuffer);

						using (VorbisReader reader = new VorbisReader(memoryStream, true))
						{
							//reader.FindNextStream();
							float[] buffer = new float[10000];

							int cnt;
							long oldSamplePosition = reader.SamplePosition;
							while ((cnt = reader.ReadSamples(buffer, 0, buffer.Length)) > 0)
							{
								totSamples += cnt / reader.Channels;
							}

							PageSamplesOffset = (int)Math.Abs(reader.TotalSamples - reader.SamplePosition);
							PageSamples = totSamples;
							PageDuration = TimeSpan.FromSeconds(totSamples / (double)reader.SampleRate);
							FirstGranulePosition = Math.Max(LastGranulePosition - totSamples, 0);
						}
					}
				}
				catch (Exception ex)
				{
					Trace.WriteLine(ex);
					return false;
				}
				return true;
			});


		}`

**Comment by ioctlLR** [comment]
How are you not getting an InvalidDataException from StreamDecoder at the line instantiating VorbisReader?  One page is _not_ enough to initialize the decoder, unless the stream in question is not spec-compliant.

How are you splitting the ogg file?

**Comment by vincenzoxx** [comment]
I read all bytes from a file. Then search and remove the header and then split all bytes at OGGs. Then mix the header with that single page, and VorbisReader doesn't give me InvalidDataException. I'm doing that to calculate FirstGranulePosition.

**Comment by ioctlLR** [comment]
Ah, now it makes sense!  Don't do that. :)

Instead of re-framing the Ogg file, you might consider doing the following:
Load the file into VorbisReader and read forward a sample at a time, keeping track of how many samples have been decoded, until you're sure you've entered the second audio data page, the stream ends, or SamplePosition is greater than your decoded sample count.  Then FirstGranulePosition = SamplePosition - numberOfSamplesDecoded.  When done, seek back to the first granule position to reset the decoder.  If the source Stream is not seek-able you'll have to buffer the decoded data until read by your other code, though with a seek-able Stream you can just seek back to the first granule position.

Another option is to write a wrapper around IPacketProvider (implementing IPacketProvider) and working with the ContainerReader and StreamDecoder types directly.  It would perform better (no decoding at all), but is more complex (VorbisReader can't be used this way).  There be dragons here...

**Comment by vincenzoxx** [comment]
Yes I could do that if the I've first page, but let's assume I'm not giving it the first page, SamplePosition will be very high for example:
I receive page from a stream started since 1h in 16khz 1 channel. Its GranulePosition would be like 960.000.000. So doing that operation I would get  960.000.000 - numberOfSamplesDecoded (that will be very small compared to SamplePosition).

**Comment by vincenzoxx** [comment]
how am I can be sure that I'm entered the second audio data page?

**Comment by ioctlLR** [comment]
The simplest calculation is 650000 / (bitrate / samplerate) samples.  That's 254 packets times the average samples per packet (the calculation goes about it a different way, but logically they are the same).  An Ogg page cannot hold more than 255 packets and the first data packet always has a sample count of zero.  There's also a >25% overrun built-in because we're dealing in averages and can't make guarantees if we just go to the average.

There are honestly better ways to do this (e.g., the IPacketProvider wrapper would give an exact calculation), but this should consistently work for you as long as the stream has a nominal bitrate.

**Comment by vincenzoxx** [comment]
Ok thanks.
